spring:
  application:
    name: xiami-blog-springcloud-config
  zipkin:
    base-url: http://localhost:9411
  cloud:
    config:
      label: main
      server:
        git:
          uri: https://github.com/youyasuxiami/spring-cloud-config.git
          search-paths: respo
          username: youyasuxiami
          password: zj12345678

server:
  #  不能改
  port: 8888
#访问文件
#web-admin-feign.yml可以访问
# http://localhost:8888/web/admin-feign/main
#或者http://localhost:8888/web-admin/feign/main
#规则如下：
#  附：HTTP 请求地址和资源文件映射
#  http://ip:port/{application}/{profile}[/{label}]
#  http://ip:port/{application}-{profile}.yml
#  http://ip:port/{label}/{application}-{profile}.yml
#  http://ip:port/{application}-{profile}.properties
#  http://ip:port/{label}/{application}-{profile}.properties

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/