#spring:
#  #客户端配置中心
#  cloud:
#    config:
#      uri: http://localhost:8888
#      #      name是配置文件的名字
#      name: zuul
#      #      分支
#      label: main
#      #      哪个配置
#      profile: dev
#


spring:
  application:
    name: xiami-blog-springcloud-zuul
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    # 自定义名字
    api-a:
      path: /api/a/**
      serviceId: xiami-blog-springcloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: xiami-blog-springcloud-web-admin-feign

