spring:
  application:
    name: xiami-blog-springcloud-web-admin-ribbon
  zipkin:
    base-url: http://localhost:9411
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/